### ISSUE TITLE
Fix Protoss Natural Wall in NightshadeLE

### ISSUE THREAD

**Issue by DrInfy** [DrInfy/sharpy-sc2#8]

**Comment by merfolk** [comment]
According to [this commit message](https://github.com/DrInfy/sharpy-sc2/commit/b88fe3a0f92176a322308da4230a794c0f6ea1e6), this bug is fixed.

> fix to nightshade map wall 

-> Close issue?

**Comment by DrInfy** [comment]
Natural wall, which I fixed
