### ISSUE TITLE
Default micro for Liberator

### ISSUE THREAD

**Issue by DrInfy** [DrInfy/sharpy-sc2#90]
**Is your feature request related to a problem? Please describe.**
Liberators just fly in and die against ground units

**Describe the solution you'd like**
Siege the liberator in a reasonable way.

**Comment by ammo-sc2** [comment]
This works okay. Not perfect, but well enough that it should be worth building some with your bio+tanks.
[micro_liberators.zip](https://github.com/DrInfy/sharpy-sc2/files/5992306/micro_liberators.zip)

**Comment by DrInfy** [comment]
It's a good start, thank you. Added that as the default liberator micro.
